title=RPG Example
version=1.0.0
width=320
height=240
scale=2
clear.r=20
clear.g=20
clear.b=30
font=fonts/font.png
world.cols=20
world.rows=15
world.tile=16
world.border=true
world.solid=5,7;6,7;7,7;8,7;9,7;15,3;15,4;15,5;15,6;15,7
